default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: <%= ENV["DB_HOST"] %>
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: bt_demo_development

test: &test
  <<: *default
  database: bt_demo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: bt_demo_production
